// Date: 2015-04-23 21:42:33
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.fogo01.ezcraft.models;

import com.fogo01.ezcraft.tileEntity.TileEntityTurbine;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelTurbine extends ModelBase {
  //fields
    ModelRenderer Base;
    ModelRenderer Shaft;
    ModelRenderer Leg1;
    ModelRenderer Leg2;
    ModelRenderer Leg3;
    ModelRenderer Leg4;
    ModelRenderer Top;
    ModelRenderer Blade11;
    ModelRenderer Blade12;
    ModelRenderer Blade21;
    ModelRenderer Blade22;
    ModelRenderer Blade31;
    ModelRenderer Blade32;
    ModelRenderer Blade41;
    ModelRenderer Blade42;
  
  public ModelTurbine() {
    textureWidth = 64;
    textureHeight = 32;

      Base = new ModelRenderer(this, 0, 0);
      Base.addBox(-8F, 0F, -8F, 16, 1, 16);
      Base.setRotationPoint(0F, 23F, 0F);
      Base.setTextureSize(64, 32);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0F);
      Top = new ModelRenderer(this, 0, 0);
      Top.addBox(-8F, 0F, -8F, 16, 1, 16);
      Top.setRotationPoint(0F, 8F, 0F);
      Top.setTextureSize(64, 32);
      Top.mirror = true;
      setRotation(Top, 0F, 0F, 0F);
      Shaft = new ModelRenderer(this, 0, 16);
      Shaft.addBox(-0.5F, -16F, -0.5F, 1, 16, 1);
      Shaft.setRotationPoint(0F, 24F, 0F);
      Shaft.setTextureSize(64, 32);
      Shaft.mirror = true;
      setRotation(Shaft, 0F, 0F, 0F);
      Leg1 = new ModelRenderer(this, 0, 16);
      Leg1.addBox(0F, -16F, 0F, 1, 16, 1);
      Leg1.setRotationPoint(-8F, 24F, -8F);
      Leg1.setTextureSize(64, 32);
      Leg1.mirror = true;
      setRotation(Leg1, 0F, 0F, 0F);
      Leg2 = new ModelRenderer(this, 0, 15);
      Leg2.addBox(0F, -16F, 0F, 1, 16, 1);
      Leg2.setRotationPoint(7F, 24F, -8F);
      Leg2.setTextureSize(64, 32);
      Leg2.mirror = true;
      setRotation(Leg2, 0F, 0F, 0F);
      Leg3 = new ModelRenderer(this, 0, 16);
      Leg3.addBox(0F, -16F, 0F, 1, 16, 1);
      Leg3.setRotationPoint(-8F, 24F, 7F);
      Leg3.setTextureSize(64, 32);
      Leg3.mirror = true;
      setRotation(Leg3, 0F, 0F, 0F);
      Leg4 = new ModelRenderer(this, 0, 16);
      Leg4.addBox(0F, -16F, 0F, 1, 16, 1);
      Leg4.setRotationPoint(7F, 24F, 7F);
      Leg4.setTextureSize(64, 32);
      Leg4.mirror = true;
      setRotation(Leg4, 0F, 0F, 0F);
      Blade11 = new ModelRenderer(this, 36, 29);
      Blade11.addBox(-6F, 0F, -1F, 12, 1, 2);
      Blade11.setRotationPoint(0F, 10F, 0F);
      Blade11.setTextureSize(64, 32);
      Blade11.mirror = true;
      setRotation(Blade11, -0.2617994F, 0F, 0F);
      Blade12 = new ModelRenderer(this, 36, 29);
      Blade12.addBox(-6F, 0F, -1F, 12, 1, 2);
      Blade12.setRotationPoint(0F, 10F, 0F);
      Blade12.setTextureSize(64, 32);
      Blade12.mirror = true;
      setRotation(Blade12, 0.2617994F, 1.570796F, 0F);
      Blade21 = new ModelRenderer(this, 36, 29);
      Blade21.addBox(-6F, 0F, -1F, 12, 1, 2);
      Blade21.setRotationPoint(0F, 13F, 0F);
      Blade21.setTextureSize(64, 32);
      Blade21.mirror = true;
      setRotation(Blade21, -0.2617994F, 0F, 0F);
      Blade22 = new ModelRenderer(this, 36, 29);
      Blade22.addBox(-6F, 0F, -1F, 12, 1, 2);
      Blade22.setRotationPoint(0F, 13F, 0F);
      Blade22.setTextureSize(64, 32);
      Blade22.mirror = true;
      setRotation(Blade22, 0.2617994F, 1.570796F, 0F);
      Blade31 = new ModelRenderer(this, 36, 29);
      Blade31.addBox(-6F, 0F, -1F, 12, 1, 2);
      Blade31.setRotationPoint(0F, 16F, 0F);
      Blade31.setTextureSize(64, 32);
      Blade31.mirror = true;
      setRotation(Blade31, -0.2617994F, 0F, 0F);
      Blade32 = new ModelRenderer(this, 36, 29);
      Blade32.addBox(-6F, 0F, -1F, 12, 1, 2);
      Blade32.setRotationPoint(0F, 16F, 0F);
      Blade32.setTextureSize(64, 32);
      Blade32.mirror = true;
      setRotation(Blade32, 0.2617994F, 1.570796F, 0F);
      Blade41 = new ModelRenderer(this, 36, 29);
      Blade41.addBox(-6F, 0F, -1F, 12, 1, 2);
      Blade41.setRotationPoint(0F, 19F, 0F);
      Blade41.setTextureSize(64, 32);
      Blade41.mirror = true;
      setRotation(Blade41, -0.2617994F, 0F, 0F);
      Blade42 = new ModelRenderer(this, 36, 29);
      Blade42.addBox(-6F, 0F, -1F, 12, 1, 2);
      Blade42.setRotationPoint(0F, 19F, 0F);
      Blade42.setTextureSize(64, 32);
      Blade42.mirror = true;
      setRotation(Blade42, 0.2617994F, 1.570796F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Base.render(f5);
    Shaft.render(f5);
    Leg1.render(f5);
    Leg2.render(f5);
    Leg3.render(f5);
    Leg4.render(f5);
    Top.render(f5);
    Blade11.render(f5);
    Blade12.render(f5);
    Blade21.render(f5);
    Blade22.render(f5);
    Blade31.render(f5);
    Blade32.render(f5);
    Blade41.render(f5);
    Blade42.render(f5);
  }

  public void renderModel(float f) {
      Base.render(f);
      Shaft.render(f);
      Leg1.render(f);
      Leg2.render(f);
      Leg3.render(f);
      Leg4.render(f);
      Top.render(f);
      Blade11.render(f);
      Blade12.render(f);
      Blade21.render(f);
      Blade22.render(f);
      Blade31.render(f);
      Blade32.render(f);
      Blade41.render(f);
      Blade42.render(f);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z) {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
