// Date: 2015-05-10 18:10:32
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.fogo01.ezcraft.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelGenerator extends ModelBase {
    //fields
    ModelRenderer Base;
    ModelRenderer Shaft;
    ModelRenderer Leg1;
    ModelRenderer Leg2;
    ModelRenderer Leg3;
    ModelRenderer Leg4;
    ModelRenderer Top;
    ModelRenderer U1;
    ModelRenderer U2;
    ModelRenderer U3;
    ModelRenderer U4;
    ModelRenderer U5;
    ModelRenderer U6;
    ModelRenderer U7;
    ModelRenderer U8;
    ModelRenderer L1;
    ModelRenderer L2;
    ModelRenderer L3;
    ModelRenderer L4;
    ModelRenderer L5;
    ModelRenderer L6;
    ModelRenderer L7;
    ModelRenderer L8;

    public ModelGenerator() {
        textureWidth = 64;
        textureHeight = 32;

        Base = new ModelRenderer(this, 0, 0);
        Base.addBox(-8F, -1F, -8F, 16, 1, 16);
        Base.setRotationPoint(0F, 24F, 0F);
        Base.setTextureSize(64, 32);
        Base.mirror = true;
        setRotation(Base, 0F, 0F, 0F);
        Shaft = new ModelRenderer(this, 4, 0);
        Shaft.addBox(-0.5F, -15F, -0.5F, 1, 14, 1);
        Shaft.setRotationPoint(0F, 24F, 0F);
        Shaft.setTextureSize(64, 32);
        Shaft.mirror = true;
        setRotation(Shaft, 0F, 0F, 0F);
        Leg1 = new ModelRenderer(this, 0, 0);
        Leg1.addBox(-0.5F, -14F, -0.5F, 1, 14, 1);
        Leg1.setRotationPoint(-7.5F, 23F, -7.5F);
        Leg1.setTextureSize(64, 32);
        Leg1.mirror = true;
        setRotation(Leg1, 0F, 0F, 0F);
        Leg2 = new ModelRenderer(this, 0, 0);
        Leg2.addBox(-0.5F, -15F, -0.5F, 1, 14, 1);
        Leg2.setRotationPoint(7.5F, 24F, -7.5F);
        Leg2.setTextureSize(64, 32);
        Leg2.mirror = true;
        setRotation(Leg2, 0F, -1.570796F, 0F);
        Leg3 = new ModelRenderer(this, 0, 0);
        Leg3.addBox(-0.5F, -15F, -0.5F, 1, 14, 1);
        Leg3.setRotationPoint(-7.5F, 24F, 7.5F);
        Leg3.setTextureSize(64, 32);
        Leg3.mirror = true;
        setRotation(Leg3, 0F, 1.570796F, 0F);
        Leg4 = new ModelRenderer(this, 0, 0);
        Leg4.addBox(-0.5F, -15F, -0.5F, 1, 14, 1);
        Leg4.setRotationPoint(7.5F, 24F, 7.5F);
        Leg4.setTextureSize(64, 32);
        Leg4.mirror = true;
        setRotation(Leg4, 0F, 3.141593F, 0F);
        Top = new ModelRenderer(this, 0, 0);
        Top.addBox(-8F, 0F, -8F, 16, 1, 16);
        Top.setRotationPoint(0F, 8F, 0F);
        Top.setTextureSize(64, 32);
        Top.mirror = true;
        setRotation(Top, 0F, 0F, 0F);
        U1 = new ModelRenderer(this, 0, 17);
        U1.addBox(-0.5F, 0F, -1.5F, 1, 4, 3);
        U1.setRotationPoint(3F, 9F, 0F);
      U1.setTextureSize(64, 32);
      U1.mirror = true;
      setRotation(U1, 0F, 0F, 0F);
      U2 = new ModelRenderer(this, 0, 17);
      U2.addBox(-0.5F, 0F, -1.5F, 1, 4, 3);
      U2.setRotationPoint(0F, 9F, 3F);
      U2.setTextureSize(64, 32);
      U2.mirror = true;
      setRotation(U2, 0F, 1.570796F, 0F);
      U3 = new ModelRenderer(this, 0, 17);
      U3.addBox(-0.5F, 0F, -1.5F, 1, 4, 3);
      U3.setRotationPoint(2F, 9F, 2F);
      U3.setTextureSize(64, 32);
      U3.mirror = true;
      setRotation(U3, 0F, -0.7853982F, 0F);
      U4 = new ModelRenderer(this, 0, 17);
      U4.addBox(-0.5F, 0F, -1.5F, 1, 4, 3);
      U4.setRotationPoint(-3F, 9F, 0F);
      U4.setTextureSize(64, 32);
      U4.mirror = true;
      setRotation(U4, 0F, 0F, 0F);
      U5 = new ModelRenderer(this, 0, 17);
      U5.addBox(-0.5F, 0F, -1.5F, 1, 4, 3);
      U5.setRotationPoint(-2F, 9F, 2F);
      U5.setTextureSize(64, 32);
      U5.mirror = true;
      setRotation(U5, 0F, 0.7853982F, 0F);
      U6 = new ModelRenderer(this, 0, 17);
      U6.addBox(-0.5F, 0F, -1.5F, 1, 4, 3);
      U6.setRotationPoint(0F, 9F, -3F);
      U6.setTextureSize(64, 32);
      U6.mirror = true;
      setRotation(U6, 0F, 1.570796F, 0F);
      U7 = new ModelRenderer(this, 0, 17);
      U7.addBox(-0.5F, 0F, -1.5F, 1, 4, 3);
      U7.setRotationPoint(-2F, 9F, -2F);
      U7.setTextureSize(64, 32);
      U7.mirror = true;
      setRotation(U7, 0F, -0.7853982F, 0F);
      U8 = new ModelRenderer(this, 0, 17);
      U8.addBox(-0.5F, 0F, -1.5F, 1, 4, 3);
      U8.setRotationPoint(2F, 9F, -2F);
      U8.setTextureSize(64, 32);
      U8.mirror = true;
      setRotation(U8, 0F, 0.7853982F, 0F);
      L1 = new ModelRenderer(this, 0, 17);
      L1.addBox(-0.5F, 0F, -1.5F, 1, 4, 3);
      L1.setRotationPoint(3F, 19F, 0F);
      L1.setTextureSize(64, 32);
      L1.mirror = true;
      setRotation(L1, 0F, 0F, 0F);
      L2 = new ModelRenderer(this, 0, 17);
      L2.addBox(-0.5F, 0F, -1.5F, 1, 4, 3);
      L2.setRotationPoint(0F, 19F, 3F);
      L2.setTextureSize(64, 32);
      L2.mirror = true;
      setRotation(L2, 0F, 1.570796F, 0F);
      L3 = new ModelRenderer(this, 0, 17);
      L3.addBox(-0.5F, 0F, -1.5F, 1, 4, 3);
      L3.setRotationPoint(2F, 19F, 2F);
      L3.setTextureSize(64, 32);
      L3.mirror = true;
      setRotation(L3, 0F, -0.7853982F, 0F);
      L4 = new ModelRenderer(this, 0, 17);
      L4.addBox(-0.5F, 0F, -1.5F, 1, 4, 3);
      L4.setRotationPoint(-3F, 19F, 0F);
      L4.setTextureSize(64, 32);
      L4.mirror = true;
      setRotation(L4, 0F, 0F, 0F);
      L5 = new ModelRenderer(this, 0, 17);
      L5.addBox(-0.5F, 0F, -1.5F, 1, 4, 3);
      L5.setRotationPoint(-2F, 19F, 2F);
      L5.setTextureSize(64, 32);
      L5.mirror = true;
      setRotation(L5, 0F, 0.7853982F, 0F);
      L6 = new ModelRenderer(this, 0, 17);
      L6.addBox(-0.5F, 0F, -1.5F, 1, 4, 3);
      L6.setRotationPoint(0F, 19F, -3F);
      L6.setTextureSize(64, 32);
      L6.mirror = true;
      setRotation(L6, 0F, 1.570796F, 0F);
      L7 = new ModelRenderer(this, 0, 17);
      L7.addBox(-0.5F, 0F, -1.5F, 1, 4, 3);
      L7.setRotationPoint(-2F, 19F, -2F);
      L7.setTextureSize(64, 32);
      L7.mirror = true;
      setRotation(L7, 0F, -0.7853982F, 0F);
      L8 = new ModelRenderer(this, 0, 17);
      L8.addBox(-0.5F, 0F, -1.5F, 1, 4, 3);
      L8.setRotationPoint(2F, 19F, -2F);
      L8.setTextureSize(64, 32);
      L8.mirror = true;
      setRotation(L8, 0F, 0.7853982F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        Base.render(f5);
        Shaft.render(f5);
        Leg1.render(f5);
        Leg2.render(f5);
        Leg3.render(f5);
        Leg4.render(f5);
        Top.render(f5);
        U1.render(f5);
        U2.render(f5);
        U3.render(f5);
        U4.render(f5);
        U5.render(f5);
        U6.render(f5);
        U7.render(f5);
        U8.render(f5);
        L1.render(f5);
        L2.render(f5);
        L3.render(f5);
        L4.render(f5);
        L5.render(f5);
        L6.render(f5);
        L7.render(f5);
        L8.render(f5);
    }

    public void renderModel(float f) {
        Base.render(f);
        Shaft.render(f);
        Leg1.render(f);
        Leg2.render(f);
        Leg3.render(f);
        Leg4.render(f);
        Top.render(f);
        U1.render(f);
        U2.render(f);
        U3.render(f);
        U4.render(f);
        U5.render(f);
        U6.render(f);
        U7.render(f);
        U8.render(f);
        L1.render(f);
        L2.render(f);
        L3.render(f);
        L4.render(f);
        L5.render(f);
        L6.render(f);
        L7.render(f);
        L8.render(f);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }

}
