// Date: 2015-07-27 22:34:00
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.fogo01.ezcraft.models;

import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelAngelWings extends ModelBiped {
  //fields
    ModelRenderer Base0;
    ModelRenderer Base1;
    ModelRenderer Base2;
    ModelRenderer Base3;
    ModelRenderer Base4;
    ModelRenderer Base5;
    ModelRenderer Base6;
    ModelRenderer Base7;
    ModelRenderer Base8;
    ModelRenderer Base9;
    ModelRenderer Base10;
    ModelRenderer Base11;
    ModelRenderer Base12;
    ModelRenderer Base13;
    ModelRenderer Base14;
    ModelRenderer Base15;
    ModelRenderer Base16;
    ModelRenderer Base17;
    ModelRenderer Base18;
    ModelRenderer Base19;

    public ModelAngelWings(float f) {
        super(f, 0, 64, 64);

        Base0 = new ModelRenderer(this, 0, 32);
        Base0.addBox(2F, 0F, 1F, 14, 8, 1, f);
        Base0.setRotationPoint(0F, 0F, 0F);
        Base0.setTextureSize(64, 64);
        Base0.mirror = true;
        setRotation(Base0, 0F, -0.3490659F, 0F);
        Base1 = new ModelRenderer(this, 30, 32);
        Base1.addBox(12F, -5F, 1F, 14, 5, 1, f);
        Base1.setRotationPoint(0F, 0F, 0F);
        Base1.setTextureSize(64, 64);
        Base1.mirror = true;
        setRotation(Base1, 0F, -0.3490659F, 0F);
        Base2 = new ModelRenderer(this, 0, 51);
        Base2.addBox(16F, 0F, 1F, 5, 5, 1, f);
        Base2.setRotationPoint(0F, 0F, 0F);
        Base2.setTextureSize(64, 64);
        Base2.mirror = true;
        setRotation(Base2, 0F, -0.3490659F, 0F);
        Base3 = new ModelRenderer(this, 0, 41);
        Base3.addBox(21F, -14F, 1F, 19, 9, 1, f);
        Base3.setRotationPoint(0F, 0F, 0F);
        Base3.setTextureSize(64, 64);
        Base3.mirror = true;
        setRotation(Base3, 0F, -0.3490659F, 0F);
        Base4 = new ModelRenderer(this, 0, 51);
        Base4.addBox(16F, -10F, 1F, 5, 5, 1, f);
        Base4.setRotationPoint(0F, 0F, 0F);
        Base4.setTextureSize(64, 64);
        Base4.mirror = true;
        setRotation(Base4, 0F, -0.3490659F, 0F);
        Base5 = new ModelRenderer(this, 12, 51);
        Base5.addBox(26F, -5F, 1F, 13, 3, 1, f);
        Base5.setRotationPoint(0F, 0F, 0F);
        Base5.setTextureSize(64, 64);
        Base5.mirror = true;
        setRotation(Base5, 0F, -0.3490659F, 0F);
        Base6 = new ModelRenderer(this, 0, 57);
        Base6.addBox(14F, -8F, 1F, 2, 3, 1, f);
        Base6.setRotationPoint(0F, 0F, 0F);
        Base6.setTextureSize(64, 64);
        Base6.mirror = true;
        setRotation(Base6, 0F, -0.3490659F, 0F);
        Base7 = new ModelRenderer(this, 6, 57);
        Base7.addBox(21F, 0F, 1F, 3, 2, 1, f);
        Base7.setRotationPoint(0F, 0F, 0F);
        Base7.setTextureSize(64, 64);
        Base7.mirror = true;
        setRotation(Base7, 0F, -0.3490659F, 0F);
        Base8 = new ModelRenderer(this, 6, 57);
        Base8.addBox(9F, -2F, 1F, 3, 2, 1, f);
        Base8.setRotationPoint(0F, 0F, 0F);
        Base8.setTextureSize(64, 64);
        Base8.mirror = true;
        setRotation(Base8, 0F, -0.3490659F, 0F);
        Base9 = new ModelRenderer(this, 0, 57);
        Base9.addBox(19F, -13F, 1F, 2, 3, 1, f);
        Base9.setRotationPoint(0F, 0F, 0F);
        Base9.setTextureSize(64, 64);
        Base9.mirror = true;
        setRotation(Base9, 0F, -0.3490659F, 0F);
        Base10 = new ModelRenderer(this, 0, 32);
        Base10.addBox(2F, 0F, -1F, 14, 8, 1, f);
        Base10.setRotationPoint(0F, 0F, 0F);
        Base10.setTextureSize(64, 64);
        Base10.mirror = true;
        setRotation(Base10, 0F, -2.792527F, 0F);
        Base11 = new ModelRenderer(this, 30, 32);
        Base11.addBox(12F, -5F, -1F, 14, 5, 1, f);
        Base11.setRotationPoint(0F, 0F, 0F);
        Base11.setTextureSize(64, 64);
        Base11.mirror = true;
        setRotation(Base11, 0F, -2.792527F, 0F);
        Base12 = new ModelRenderer(this, 0, 51);
        Base12.addBox(16F, 0F, -1F, 5, 5, 1, f);
        Base12.setRotationPoint(0F, 0F, 0F);
        Base12.setTextureSize(64, 64);
        Base12.mirror = true;
        setRotation(Base12, 0F, -2.792527F, 0F);
        Base13 = new ModelRenderer(this, 0, 41);
        Base13.addBox(21F, -14F, -1F, 19, 9, 1, f);
        Base13.setRotationPoint(0F, 0F, 0F);
        Base13.setTextureSize(64, 64);
        Base13.mirror = true;
        setRotation(Base13, 0F, -2.792527F, 0F);
        Base14 = new ModelRenderer(this, 0, 51);
        Base14.addBox(16F, -10F, -1F, 5, 5, 1, f);
        Base14.setRotationPoint(0F, 0F, 0F);
        Base14.setTextureSize(64, 64);
        Base14.mirror = true;
        setRotation(Base14, 0F, -2.792527F, 0F);
        Base15 = new ModelRenderer(this, 12, 51);
        Base15.addBox(26F, -5F, -1F, 13, 3, 1, f);
        Base15.setRotationPoint(0F, 0F, 0F);
        Base15.setTextureSize(64, 64);
        Base15.mirror = true;
        setRotation(Base15, 0F, -2.792527F, 0F);
        Base16 = new ModelRenderer(this, 0, 57);
        Base16.addBox(14F, -8F, -1F, 2, 3, 1, f);
        Base16.setRotationPoint(0F, 0F, 0F);
        Base16.setTextureSize(64, 64);
        Base16.mirror = true;
        setRotation(Base16, 0F, -2.792527F, 0F);
        Base17 = new ModelRenderer(this, 6, 57);
        Base17.addBox(21F, 0F, -1F, 3, 2, 1, f);
        Base17.setRotationPoint(0F, 0F, 0F);
        Base17.setTextureSize(64, 64);
        Base17.mirror = true;
        setRotation(Base17, 0F, -2.792527F, 0F);
        Base18 = new ModelRenderer(this, 6, 57);
        Base18.addBox(9F, -2F, -1F, 3, 2, 1, f);
        Base18.setRotationPoint(0F, 0F, 0F);
        Base18.setTextureSize(64, 64);
        Base18.mirror = true;
        setRotation(Base18, 0F, -2.792527F, 0F);
        Base19 = new ModelRenderer(this, 0, 57);
        Base19.addBox(19F, -13F, -1F, 2, 3, 1, f);
        Base19.setRotationPoint(0F, 0F, 0F);
        Base19.setTextureSize(64, 64);
        Base19.mirror = true;
        setRotation(Base19, 0F, -2.792527F, 0F);

        this.bipedBody.addChild(Base0);
        this.bipedBody.addChild(Base1);
        this.bipedBody.addChild(Base2);
        this.bipedBody.addChild(Base3);
        this.bipedBody.addChild(Base4);
        this.bipedBody.addChild(Base5);
        this.bipedBody.addChild(Base6);
        this.bipedBody.addChild(Base7);
        this.bipedBody.addChild(Base8);
        this.bipedBody.addChild(Base9);

        this.bipedBody.addChild(Base10);
        this.bipedBody.addChild(Base11);
        this.bipedBody.addChild(Base12);
        this.bipedBody.addChild(Base13);
        this.bipedBody.addChild(Base14);
        this.bipedBody.addChild(Base15);
        this.bipedBody.addChild(Base16);
        this.bipedBody.addChild(Base17);
        this.bipedBody.addChild(Base18);
        this.bipedBody.addChild(Base19);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        /*
        Base0.render(f5);
        Base1.render(f5);
        Base2.render(f5);
        Base3.render(f5);
        Base4.render(f5);
        Base5.render(f5);
        Base6.render(f5);
        Base7.render(f5);
        Base8.render(f5);
        Base9.render(f5);
        Base10.render(f5);
        Base11.render(f5);
        Base12.render(f5);
        Base13.render(f5);
        Base14.render(f5);
        Base15.render(f5);
        Base16.render(f5);
        Base17.render(f5);
        Base18.render(f5);
        Base19.render(f5);
        */
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }

}
